### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by heron2014** [heron2014/email-charmer#9]
Currently I am sending back not quite a very good match to selected word. Check out the response object to get more relevant suggestion. 
- [x] explore other suggestions from response object

Also API can't match words which are surrounded by special characters like: ```. , ? !``` 
- [x] strip off the word from any special characters, lowerCase it as well before request to API

Also another issue is with selecting words by clicking on FIRST and LAST throws an errror:

```script.js:13 Uncaught DOMException: Failed to execute 'setEnd' on 'Range': The offset 28 is larger than or equal to the node's length (27).```

- [ ] investigate and fix it

The new suggested word convert into HTML element and append it to bodyMessage. 
- [ ] check out if the above solution works
- [x] custom alert (for now as it is simple and quick solution)
- [ ] ideally tooltip would be great!

**Comment by heron2014** [comment]
http://stackoverflow.com/questions/7853130/how-to-change-the-style-of-alert-box
